CREATE SCHEMA IF NOT EXISTS gestion_comision AUTHORIZATION gabrielo;

DO $$
BEGIN
  PERFORM 1 FROM pg_roles WHERE rolname = 'rcompensacion_comision';
  IF NOT FOUND THEN CREATE ROLE rcompensacion_comision NOLOGIN; END IF;

  PERFORM 1 FROM pg_roles WHERE rolname = 'rmonitorizacion_compensacion_comision';
  IF NOT FOUND THEN CREATE ROLE rmonitorizacion_compensacion_comision NOLOGIN; END IF;

  PERFORM 1 FROM pg_roles WHERE rolname = 'rmantenimiento_compensacion_comision';
  IF NOT FOUND THEN CREATE ROLE rmantenimiento_compensacion_comision NOLOGIN; END IF;

  PERFORM 1 FROM pg_roles WHERE rolname = 'rcompensacion_comision_meta4';
  IF NOT FOUND THEN CREATE ROLE rcompensacion_comision_meta4 NOLOGIN; END IF;

  PERFORM 1 FROM pg_roles WHERE rolname = 'rservicios_sil_sistema_informacional';
  IF NOT FOUND THEN CREATE ROLE rservicios_sil_sistema_informacional NOLOGIN; END IF;

  PERFORM 1 FROM pg_roles WHERE rolname = 'rreporting_sil_sistema_informacional';
  IF NOT FOUND THEN CREATE ROLE rreporting_sil_sistema_informacional NOLOGIN; END IF;

  PERFORM 1 FROM pg_roles WHERE rolname = 'rmantenimiento_income';
  IF NOT FOUND THEN CREATE ROLE rmantenimiento_income NOLOGIN; END IF;
END$$;

CREATE TABLE IF NOT EXISTS gestion_comision.accion (
    id_accion                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                    VARCHAR(128)  NOT NULL,
    descripcion               VARCHAR(255)  NOT NULL,
    reaccion_peso             INTEGER,
    es_reaccion_esperar       BOOLEAN       NOT NULL,
    es_reaccion_reintento     BOOLEAN       NOT NULL,
    reaccion_reintento_max    INTEGER,
    reaccion_reintento_delay  INTEGER
);

COMMENT ON TABLE gestion_comision.accion IS
  'Tabla con los tipos de acciones de comprobación de datos: motivosDesplazamientoV1, condicionesHistoricoV1, fechasV1, presenciasV1...';

COMMENT ON COLUMN gestion_comision.accion.id_accion IS 'Identificador de la acción';
COMMENT ON COLUMN gestion_comision.accion.nombre IS 'Nombre de la acción motivosDesplazamientoV1 condicionesHistoricoV1, fechasV1...';
COMMENT ON COLUMN gestion_comision.accion.descripcion IS 'Descripción de la acción';
COMMENT ON COLUMN gestion_comision.accion.reaccion_peso IS 'Peso, define el peso de una acción sobre otras';
COMMENT ON COLUMN gestion_comision.accion.es_reaccion_esperar IS 'Flag que indica si hay que usar delay';
COMMENT ON COLUMN gestion_comision.accion.es_reaccion_reintento IS 'Flag que indica si hay que reintentar';
COMMENT ON COLUMN gestion_comision.accion.reaccion_reintento_max IS 'Numero maximo de reintentos';
COMMENT ON COLUMN gestion_comision.accion.reaccion_reintento_delay IS 'Delay en los reintentos';

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE gestion_comision.accion TO rcompensacion_comision;
GRANT SELECT ON TABLE gestion_comision.accion TO rmonitorizacion_compensacion_comision;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE gestion_comision.accion TO rmantenimiento_compensacion_comision;
GRANT SELECT ON TABLE gestion_comision.accion TO rcompensacion_comision_meta4;
GRANT SELECT ON TABLE gestion_comision.accion TO rservicios_sil_sistema_informacional;
GRANT SELECT ON TABLE gestion_comision.accion TO rreporting_sil_sistema_informacional;
GRANT INSERT, SELECT, UPDATE ON TABLE gestion_comision.accion TO rmantenimiento_income;
