spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/rent
    username: gabrielo
    password: gabrielo

  flyway:
    enabled: false
    locations: classpath:db/migration
    validate-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

logging:
  level:
    org:
      flywaydb: INFO

