CREATE SCHEMA IF NOT EXISTS gestion_comision;


CREATE TABLE IF NOT EXISTS gestion_comision.accion (
    id_accion                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                    VARCHAR(128)  NOT NULL,
    descripcion               VARCHAR(255)  NOT NULL,
    reaccion_peso             INTEGER,
    es_reaccion_esperar       BOOLEAN       NOT NULL,
    es_reaccion_reintento     BOOLEAN       NOT NULL,
    reaccion_reintento_max    INTEGER,
    reaccion_reintento_delay  INTEGER
);

COMMENT ON TABLE gestion_comision.accion IS
  'Tabla con los tipos de acciones de comprobación de datos: motivosDesplazamientoV1, condicionesHistoricoV1, fechasV1, presenciasV1...';

COMMENT ON COLUMN gestion_comision.accion.id_accion IS 'Identificador de la acción';
COMMENT ON COLUMN gestion_comision.accion.nombre IS 'Nombre de la acción motivosDesplazamientoV1 condicionesHistoricoV1, fechasV1...';
COMMENT ON COLUMN gestion_comision.accion.descripcion IS 'Descripción de la acción';
COMMENT ON COLUMN gestion_comision.accion.reaccion_peso IS 'Peso, define el peso de una acción sobre otras';
COMMENT ON COLUMN gestion_comision.accion.es_reaccion_esperar IS 'Flag que indica si hay que usar delay';
COMMENT ON COLUMN gestion_comision.accion.es_reaccion_reintento IS 'Flag que indica si hay que reintentar';
COMMENT ON COLUMN gestion_comision.accion.reaccion_reintento_max IS 'Numero maximo de reintentos';
COMMENT ON COLUMN gestion_comision.accion.reaccion_reintento_delay IS 'Delay en los reintentos';
