spring.datasource.url=jdbc:postgresql://localhost:5433/rent
spring.datasource.username=gabrielo
spring.datasource.password=gabrielo

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.flywaydb=INFO

